import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Link from "next/link";
import { headers } from "next/headers";
import Image from "next/image";
import Avatar from "@/app/assets/elon.webp";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const currentUrl = headersList.get("x-nextjs-route"); // The current path
  console.log(currentUrl);
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="page-header">
          <div className="brand">
            <Link href="/">
              <p>BitSindri</p>
            </Link>
          </div>
          <p>{currentUrl}</p>
          <div className="avatar">
            <Image
              src={Avatar}
              width={1280}
              height={1280}
              objectFit="cover"
              alt="avatar"
            />
          </div>
        </div>
        <div className="flex">
          <Sidebar />

          {children}
        </div>
      </body>
    </html>
  );
}
